name: Create new translation version branch in language repository

on:
  workflow_call:
    inputs:
      source_branch:
        required: true
        type: string
      source_folder:
        required: true
        type: string
      new_branch_name:
         required: true
         type: string

jobs:
  pull_and_create_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Set up Git with GitHub Actions bot identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Pull content from another repository
        run: |
          git clone --branch ${{ inputs.source_branch }} --single-branch https://github.com/owaspsamm/core temp-repo
          rm -rf temp-repo/.git
          rsync -a --exclude='.git' temp-repo/ .
      - name: Create a new branch with the pulled content
        run: |
          git checkout -b ${{ inputs.new_branch_name }}
          git add ${{ inputs.source_folder }}
          git commit -m "Pulled content from ${{ inputs.source_repo }}:${{ inputs.source_branch }}"
          git push origin ${{ inputs.new_branch_name }}
